import requests
from flask import jsonify
from flask import Flask, render_template, request

OMDB_API_KEY = '1cc488d6'

app = Flask(__name__)

book1 = [
            {"title": "Abbot & Costello: Jack & the Beanstalk", "book": "Book 1", "page": 1, "slot":1},
            {"title": "About a Boy", "book": "Book 1", "page": 1, "slot":2},
            {"title": "Adventures in Babysitting", "book": "Book 1", "page": 1, "slot":3},
            {"title": "Adventures in the Wild", "book": "Book 1", "page": 1, "slot":4},
            {"title": "The Adventures of Milo and Otis", "book": "Book 1", "page": 2, "slot":1},
            {"title": "The Adventures of Sharkboy and Lavagirl", "book": "Book 1", "page": 2, "slot":2},
            {"title": "All Dogs Go To Heaven", "book": "Book 1", "page": 2, "slot":3},
            {"title": "American Assassin", "book": "Book 1", "page": 2, "slot":4},
            {"title": "American Graffiti", "book": "Book 1", "page": 3, "slot":1},
            {"title": "Anchorman: The Legend of Ron Burgundy", "book": "Book 1", "page": 3, "slot":2},
            {"title": "The Andy Griffith Show", "book": "Book 1", "page": 3, "slot":3},
            {"title": "Andre", "book": "Book 1", "page": 3, "slot":4},
            {"title": "Animal House", "book": "Book 1", "page": 4, "slot":1},
            {"title": "Annie (1981)", "book": "Book 1", "page": 4, "slot":2},
            {"title": "Annie (2014)", "book": "Book 1", "page": 4, "slot":3},
            {"title": "Ant-Man", "book": "Book 1", "page": 4, "slot":4},
            {"title": "Ant-Man and The Wasp", "book": "Book 1", "page": 5, "slot":1},
            {"title": "Aquaman", "book": "Book 1", "page": 5, "slot":2},
            {"title": "The Aristocats", "book": "Book 1", "page": 5, "slot":3},
            {"title": "Austin Powers: The Spy Who Shagged Me", "book": "Book 1", "page": 5, "slot":4},
            {"title": "Austin Powers: Goldmember", "book": "Book 1", "page": 6, "slot":1},
            {"title": "The Avengers", "book": "Book 1", "page": 6, "slot":2},
            {"title": "Avengers: Infinity War", "book": "Book 1", "page": 6, "slot":3},
            {"title": "Avatar", "book": "Book 1", "page": 6, "slot":4},
            {"title": "Babe", "book": "Book 1", "page": 7, "slot":1},
            {"title": "Bachelor Party", "book": "Book 1", "page": 7, "slot":2},
            {"title": "Back to the Future", "book": "Book 1", "page": 7, "slot":3},
            {"title": "Back to the Future Part II", "book": "Book 1", "page": 7, "slot":4},
            {"title": "Back to the Future Part III", "book": "Book 1", "page": 8, "slot":1},
            {"title": "Balto III: Wings of Change", "book": "Book 1", "page": 8, "slot":2},
            {"title": "Batman Begins", "book": "Book 1", "page": 8, "slot":3},
            {"title": "Batman v Superman: Dawn of Justice", "book": "Book 1", "page": 8, "slot":4},
            {"title": "The Lego Batman Movie", "book": "Book 1", "page": 9, "slot":1},
            {"title": "Battle of Britain", "book": "Book 1", "page": 9, "slot":2},
            {"title": "Because of Winn-Dixie", "book": "Book 1", "page": 9, "slot":3},
            {"title": "Bedknobs and Broomsticks", "book": "Book 1", "page": 9, "slot":4},
            {"title": "Bee Movie", "book": "Book 1", "page": 10, "slot":1},
            {"title": "Beetlejuice", "book": "Book 1", "page": 10, "slot":2},
            {"title": "Bend It Like Beckham", "book": "Book 1", "page": 10, "slot":3},
            {"title": "Benji", "book": "Book 1", "page": 10, "slot":4},
            {"title": "Benji Off the Leash!", "book": "Book 1", "page": 10, "slot":4},
            {"title": "For the Love of Benji", "book": "Book 1", "page": 10, "slot":4},
            {"title": "Benji's Very Own Christmas Story", "book": "Book 1", "page": 10, "slot":4},
            {"title": "Big", "book": "Book 1", "page": 11, "slot":1},
            {"title": "The Big Boss", "book": "Book 1", "page": 11, "slot":2},
            {"title": "Big Hero 6", "book": "Book 1", "page": 11, "slot":3},
            {"title": "The Big Lebowski", "book": "Book 1", "page": 11, "slot":4},
            {"title": "Big Trouble in Little China", "book": "Book 1", "page": 12, "slot":1},
            {"title": "Blazing Saddles", "book": "Book 1", "page": 12, "slot":2},
            {"title": "Black Hawk Down", "book": "Book 1", "page": 12, "slot":3},
            {"title": "Black Mask", "book": "Book 1", "page": 12, "slot":4},
            {"title": "The Blind Side", "book": "Book 1", "page": 13, "slot":1},
            {"title": "The Blues Brothers", "book": "Book 1", "page": 13, "slot":2},
            {"title": "Boogie Nights", "book": "Book 1", "page": 13, "slot":3},
            {"title": "Bourne Supremacy", "book": "Book 1", "page": 13, "slot":4},
            {"title": "Breakfast at Tiffany's", "book": "Book 1", "page": 14, "slot":1},
            {"title": "The Breakfast Club", "book": "Book 1", "page": 14, "slot":2},
            {"title": "The Break-Up", "book": "Book 1", "page": 14, "slot":3},
            {"title": "Air Buddies", "book": "Book 1", "page": 14, "slot":4},
            {"title": "Snow Buddies", "book": "Book 1", "page": 15, "slot":1},
            {"title": "Space Buddies", "book": "Book 1", "page": 15, "slot":2},
            {"title": "Santa Buddies", "book": "Book 1", "page": 15, "slot":3},
            {"title": "Santa Paws", "book": "Book 1", "page": 15, "slot":4},
            {"title": "Spooky Buddies", "book": "Book 1", "page": 16, "slot":1},
            {"title": "Treasure Buddies", "book": "Book 1", "page": 16, "slot":2},
            {"title": "Super Buddies", "book": "Book 1", "page": 16, "slot":3},
            {"title": "Bodyguards and Assassins", "book": "Book 1", "page": 16, "slot":4},
            {"title": "Bolt", "book": "Book 1", "page": 17, "slot":1},
            {"title": "Cars", "book": "Book 1", "page": 17, "slot":2},
            {"title": "Cars 2", "book": "Book 1", "page": 17, "slot":3},
            {"title": "Cars 3", "book": "Book 1", "page": 17, "slot":4},
            {"title": "Cartoon Craze Presents: All-Stars Vol. 1", "book": "Book 1", "page": 18, "slot":1},
            {"title": "Cast Away", "book": "Book 1", "page": 18, "slot":2},
            {"title": "Cats & Dogs", "book": "Book 1", "page": 18, "slot":3},
            {"title": "Captain America: The First Avenger", "book": "Book 1", "page": 18, "slot":4},
            {"title": "Captain America: The Winter Soldier", "book": "Book 1", "page": 19, "slot":1},
            {"title": "Captain America: Civil War", "book": "Book 1", "page": 19, "slot":2},
            {"title": "Captain Marvel", "book": "Book 1", "page": 19, "slot":3},
            {"title": "Captain Ron", "book": "Book 1", "page": 19, "slot":4},
            {"title": "Charlotte's Web (1973)", "book": "Book 1", "page": 20, "slot":1},
            {"title": "Charlotte's Web (2006)", "book": "Book 1", "page": 20, "slot":2},
            {"title": "Cheaper by the Dozen", "book": "Book 1", "page": 20, "slot":3},
            {"title": "Chicken Run", "book": "Book 1", "page": 20, "slot":4},
            {"title": "Classic Comedy", "book": "Book 1", "page": 21, "slot":1},
            {"title": "Chocolate", "book": "Book 1", "page": 21, "slot":2},
            {"title": "Christmas Eve Cinema", "book": "Book 1", "page": 21, "slot":3},
            {"title": "Cloudy With a Chance of Meatballs", "book": "Book 1", "page": 21, "slot":4},
            {"title": "Cloudy With a Chance of Meatballs 2", "book": "Book 1", "page": 22, "slot":1},
            {"title": "Clue", "book": "Book 1", "page": 22, "slot":2},
            {"title": "The Color of Money", "book": "Book 1", "page": 22, "slot":3},
            {"title": "The Commitments", "book": "Book 1", "page": 22, "slot":4},
            {"title": "Cool Runnings", "book": "Book 1", "page": 23, "slot":1},
            {"title": "Crank", "book": "Book 1", "page": 23, "slot":2},
            {"title": "The Croods", "book": "Book 1", "page": 23, "slot":3},
            {"title": "Daddy Day Care", "book": "Book 1", "page": 23, "slot":4},
            {"title": "Daddy Day Camp", "book": "Book 1", "page": 23, "slot":4},
            {"title": "The Day After Tomorrow", "book": "Book 1", "page": 24, "slot":1},
            {"title": "Days of Thunder", "book": "Book 1", "page": 24, "slot":2},
            {"title": "Deliverance", "book": "Book 1", "page": 24, "slot":3},
            {"title": "Despicable Me", "book": "Book 1", "page": 24, "slot":4},
            {"title": "Despicable Me 2", "book": "Book 1", "page": 25, "slot":1},
            {"title": "Detective Pikachu", "book": "Book 1", "page": 25, "slot":2},
            {"title": "Diary of a Wimpy Kid", "book": "Book 1", "page": 25, "slot":3},
            {"title": "Diary of a Wimpy Kid: Rodrick Rules", "book": "Book 1", "page": 25, "slot":4},
            {"title": "Diary of a Wimpy Kid: Dog Days", "book": "Book 1", "page": 26, "slot":1},
            {"title": "Die Hard", "book": "Book 1", "page": 26, "slot":2},
            {"title": "Die Hard 2", "book": "Book 1", "page": 26, "slot":3},
            {"title": "Die Hard With a Vengance", "book": "Book 1", "page": 26, "slot":4},
            {"title": "Live Free Die Hard", "book": "Book 1", "page": 27, "slot":1},
            {"title": "A Good Day to Die Hard", "book": "Book 1", "page": 27, "slot":2},
            {"title": "Divergent", "book": "Book 1", "page": 27, "slot":3},
            {"title": "Insurgent", "book": "Book 1", "page": 27, "slot":4},
            {"title": "Allegiant", "book": "Book 1", "page": 28, "slot":1},
            {"title": "Dogma: A True Underdog Story", "book": "Book 1", "page": 28, "slot":2},
            {"title": "Dr. Dolittle", "book": "Book 1", "page": 28, "slot":3},
            {"title": "Dr. Dolittle 2", "book": "Book 1", "page": 28, "slot":4},
            {"title": "The Doors", "book": "Book 1", "page": 29, "slot":1},
            {"title": "Dragonheart", "book": "Book 1", "page": 29, "slot":2},
            {"title": "Dreamer", "book": "Book 1", "page": 29, "slot":3},
            {"title": "Dream Girls", "book": "Book 1", "page": 29, "slot":4},
            {"title": "Dumbo (1941)", "book": "Book 1", "page": 30, "slot":1},
            {"title": "Disney Nature: Earth", "book": "Book 1", "page": 30, "slot":2},
            {"title": "Earth to Echo", "book": "Book 1", "page": 30, "slot":3},
            {"title": "Eight Below", "book": "Book 1", "page": 30, "slot":4},
            {"title": "8 Seconds", "book": "Book 1", "page": 31, "slot":1},
            {"title": "An Empress and The Warriors", "book": "Book 1", "page": 31, "slot":2},
            {"title": "Ender's Game", "book": "Book 1", "page": 31, "slot":3},
            {"title": "The Encounter", "book": "Book 1", "page": 31, "slot":4},
            {"title": "Enter the Dragon", "book": "Book 1", "page": 30, "slot":1},
            {"title": "Epic", "book": "Book 1", "page": 30, "slot":2},
            {"title": "Ernest Goes to Camp", "book": "Book 1", "page": 30, "slot":3},
            {"title": "Ernest Goes to Jail", "book": "Book 1", "page": 30, "slot":3},
            {"title": "Ernest: Scared Stupid", "book": "Book 1", "page": 30, "slot":4},
            {"title": "Eureka", "book": "Book 1", "page": 31, "slot":1},
            {"title": "Expelled", "book": "Book 1", "page": 31, "slot":2},
            {"title": "Explorers", "book": "Book 1", "page": 31, "slot":3},
            {"title": "E.T. The Extra-Terrestrial", "book": "Book 1", "page": 31, "slot":4},
            {"title": "Failure to Launch", "book": "Book 1", "page": 32, "slot":1},
            {"title": "George w. Bush: Faith in the White House", "book": "Book 1", "page": 32, "slot":2},
            {"title": "The Family Man", "book": "Book 1", "page": 32, "slot":3},
            {"title": "Fantastic 4: Rise of the Silver Surfer", "book": "Book 1", "page": 32, "slot":4},
            {"title": "Fantasia", "book": "Book 1", "page": 33, "slot":1},
            {"title": "Fantasia 2000", "book": "Book 1", "page": 33, "slot":2},
            {"title": "Fantastic Beasts and Where to Find Them", "book": "Book 1", "page": 33, "slot":3},
            {"title": "Fantastic Beasts: The Crimes of Grindelwald", "book": "Book 1", "page": 33, "slot":4},
            {"title": "The Fast and the Furious", "book": "Book 1", "page": 34, "slot":1},
            {"title": "2 Fast 2 Furious", "book": "Book 1", "page": 34, "slot":2},
            {"title": "The Fast and the Furious: Tokyo Drift", "book": "Book 1", "page": 34, "slot":3},
            {"title": "Fast & Furious", "book": "Book 1", "page": 34, "slot":4},
            {"title": "Fast Five", "book": "Book 1", "page": 35, "slot":1},
            {"title": "Fast & Furious 6", "book": "Book 1", "page": 35, "slot":2},
            {"title": "Furious 7", "book": "Book 1", "page": 35, "slot":3},
            {"title": "The Fate of the Furious", "book": "Book 1", "page": 35, "slot":4},
            {"title": "Fast & Furious: Hobbs & Shaw", "book": "Book 1", "page": 36, "slot":1},
            {"title": "Fast Times at Ridgemont High", "book": "Book 1", "page": 36, "slot":2},
            {"title": "Ferngully: The Last Rainforest", "book": "Book 1", "page": 36, "slot":3},
            {"title": "Ferris Bueller's Day Off", "book": "Book 1", "page": 36, "slot":4},
            {"title": "Fiddler on the Roof", "book": "Book 1", "page": 37, "slot":1},
            {"title": "Fireproof: Never Leave Your Partner Behind", "book": "Book 1", "page": 37, "slot":2},
            {"title": "The Fifth Element", "book": "Book 1", "page": 37, "slot":3},
            {"title": "Finding Nemo", "book": "Book 1", "page": 37, "slot":4},
            {"title": "Finding Dory", "book": "Book 1", "page": 38, "slot":1},
            {"title": "First Daughter", "book": "Book 1", "page": 38, "slot":2},
            {"title": "Fist of Fury", "book": "Book 1", "page": 38, "slot":3},
            {"title": "Five People You Meet in Heaven", "book": "Book 1", "page": 38, "slot":4},
            {"title": "Flags of our Fathers", "book": "Book 1", "page": 39, "slot":1},
            {"title": "Flicka", "book": "Book 1", "page": 39, "slot":2},
            {"title": "Flight of the Navigator", "book": "Book 1", "page": 39, "slot":3},
            {"title": "Flightplan", "book": "Book 1", "page": 39, "slot":4},
            {"title": "Flywheel", "book": "Book 1", "page": 40, "slot":1},
            {"title": "14 Blades", "book": "Book 1", "page": 40, "slot":2},
            {"title": "The Fox and the Hound", "book": "Book 1", "page": 40, "slot":3},
            {"title": "Frozen", "book": "Book 1", "page": 40, "slot":4},
            {"title": "Full Metal Jacket", "book": "Book 1", "page": 40, "slot":1},
            {"title": "Game of Death", "book": "Book 1", "page": 41, "slot":2},
            {"title": "Game of Death II", "book": "Book 1", "page": 41, "slot":3},
            {"title": "Garfield (2004)", "book": "Book 1", "page": 41, "slot":4},
            {"title": "Garfield's Pet Force", "book": "Book 1", "page": 42, "slot":1},
            {"title": "Get Smart: The Complete Series (1995)", "book": "Book 1", "page": 42, "slot":2},
            {"title": "G.I. Joe Seasons 1-3 (1985)", "book": "Book 1", "page": 42, "slot":3},
            {"title": "G-Force", "book": "Book 1", "page": 42, "slot":4},
            {"title": "Ghostbusters", "book": "Book 1", "page": 43, "slot":1},
            {"title": "Gladiator", "book": "Book 1", "page": 43, "slot":2},
            {"title": "Gods and Generals", "book": "Book 1", "page": 43, "slot":3},
            {"title": "God's Little Creatures", "book": "Book 1", "page": 43, "slot":4},
            {"title": "God's Not Dead", "book": "Book 1", "page": 44, "slot":1},
            {"title": "Good Morning Vietnam", "book": "Book 1", "page": 44, "slot":2},
            {"title": "Good Will Hunting", "book": "Book 1", "page": 44, "slot":3},
            {"title": "The Goonies", "book": "Book 1", "page": 44, "slot":4},
            {"title": "Gravity Falls: Six Strange Tales", "book": "Book 1", "page": 45, "slot":1},
            {"title": "The Greatest Game Ever Played", "book": "Book 1", "page": 45, "slot":2},
            {"title": "Greatest Heroes Legends: David & Goliath", "book": "Book 1", "page": 45, "slot":3},
            {"title": "The Greatest Showman", "book": "Book 1", "page": 45, "slot":4},
            {"title": "Green Lantern", "book": "Book 1", "page": 46, "slot":1},
            {"title": "Groundhog Day", "book": "Book 1", "page": 46, "slot":2},
            {"title": "Grown Ups", "book": "Book 1", "page": 46, "slot":3},
            {"title": "Grown Ups 2", "book": "Book 1", "page": 46, "slot":4},
            {"title": "Guardian", "book": "Book 1", "page": 47, "slot":1},
            {"title": "Guardians of the Galaxy", "book": "Book 1", "page": 47, "slot":2},
            {"title": "Guardians of the Galaxy Vol. 2", "book": "Book 1", "page": 47, "slot":3},
            {"title": "Hancock", "book": "Book 1", "page": 47, "slot":4},
            {"title": "The Hangover", "book": "Book 1", "page": 48, "slot":1},
            {"title": "Happy Feet", "book": "Book 1", "page": 48, "slot":2},
            {"title": "Happy Feet Two", "book": "Book 1", "page": 48, "slot":3},
            {"title": "Harry Potter and the Sorcerer's Stone", "book": "Book 1", "page": 48, "slot":4},
            {"title": "Harry Potter and the Chamber of Secrets", "book": "Book 1", "page": 49, "slot":1},
            {"title": "Harry Potter and the Goblet of Fire", "book": "Book 1", "page": 49, "slot":2},
            {"title": "Harry Potter and the Order of the Phoenix", "book": "Book 1", "page": 49, "slot":3},
            {"title": "Harry Potter and the Half-Blood Prince", "book": "Book 1", "page": 49, "slot":4},
            {"title": "Harry Potter and the Deathly Hallows Part 1", "book": "Book 1", "page": 50, "slot":1},
            {"title": "Harry Potter and the Deathly Hallows: Part 2", "book": "Book 1", "page": 50, "slot":2},
            {"title": "He-Man and the Masters of the Universe Volume 2 (1983)", "book": "Book 1", "page": 50, "slot":3},
            {"title": "Here Comes the Boom", "book": "Book 1", "page": 50, "slot":4},
            {"title": "Paul Blart Mall Cop", "book": "Book 1", "page": 50, "slot":4}
        ]
book2 = [
            {"title": "The Matrix", "book": "Book 2", "page": 1, "slot":1},
            {"title": "seven", "book": "Book 2", "page": 1, "slot":2},
            {"title": "eight", "book": "Book 2", "page": 1, "slot":3},
            {"title": "nine", "book": "Book 2", "page": 1, "slot":4},
            {"title": "ten", "book": "Book 2", "page": 2, "slot":1}
         ]
book3 = [
            {"title": "eleven", "book": "Book 3", "page": 1, "slot":1},
            {"title": "twelve", "book": "Book 3", "page": 1, "slot":2},
            {"title": "thirteen", "book": "Book 3", "page": 1, "slot":3},
            {"title": "fourteen", "book": "Book 3", "page": 1, "slot":4},
            {"title": "fifteen", "book": "Book 3", "page": 2, "slot":1}
         ]
book4 = [
            {"title": "sixteen", "book": "Book 4", "page": 1, "slot":1},
            {"title": "seventeen", "book": "Book 4", "page": 1, "slot":2},
            {"title": "eighteen", "book": "Book 4", "page": 1, "slot":3},
            {"title": "nineteen", "book": "Book 4", "page": 1, "slot":4},
            {"title": "twenty", "book": "Book 4", "page": 2, "slot":1}
        ]

@app.route('/')
def index():
    all_books = book1 + book2 + book3 + book4
    return render_template('index.html', dvds=all_books)

@app.route('/check', methods=['POST'])
def check():
    data = request.json
    item = data.get('item', '').strip().lower()
    all_books = book1 + book2 + book3 + book4
    for dvd in all_books:
        if dvd["title"].lower() == item:
            # Fetch OMDb info
            omdb_url = f"http://www.omdbapi.com/?t={dvd['title']}&apikey={OMDB_API_KEY}"
            omdb_response = requests.get(omdb_url, timeout = 5)
            omdb_data = omdb_response.json()
            # Prepare result
            result = {
                'location': f'{dvd["book"]}, Page {dvd["page"]}, Slot {dvd["slot"]}',
                'omdb': {
                    'Title': omdb_data.get('Title', 'N/A'),
                    'Year': omdb_data.get('Year', 'N/A'),
                    'Rated': omdb_data.get('Rated', 'N/A'),
                    'Released': omdb_data.get('Released', 'N/A'),
                    'Runtime': omdb_data.get('Runtime', 'N/A'),
                    'Genre': omdb_data.get('Genre', 'N/A'),
                    'Director': omdb_data.get('Director', 'N/A'),
                    'Actors': omdb_data.get('Actors', 'N/A'),
                    'Plot': omdb_data.get('Plot', 'N/A'),
                    'Ratings': omdb_data.get('Ratings', []),
                    'Poster': omdb_data.get('Poster', '')
                }
            }
            return jsonify(result)
    return jsonify({'result': 'Not found. Try checking the title or manually checking the books.'})
if __name__ == '__main__':
    app.run(debug=True)